### ISSUE TITLE
Does not start - Issues message: library(issuer) Error in username() : could not find function "username"

### ISSUE THREAD

**Issue by dsbitor** [WilDoane/issuer#1]
Get Rstudio msg box 
Error Executing Addin
: could not find function "username"

Tried:
> library(devtools)
Loading required package: usethis
> library (usethis)
> library(devtools)
> library(devtools)
> library(issuer)

Did not work either producing above message.

RStudio version: Version 1.2.1502
Build 1356 (c9572467, 2019-04-16)

**Comment by WilDoane** [comment]
Caused by a silly last minute function name change.   
  

  
Resolved and tested. Please try reinstalling.   
  
  
  
  

  
  
>
